<h1>Crop Prediction using Support Vector Machines</h1>

<h4>Dhrithi.P.Alva 1MS17CS028</h4>
<h4>Gautam Mundada 1MS17CS033</h4>
<h4>Harivind Premkumar 1MS17CS034</h4>
<h4>Kiran M.H.M 1MS17CS046</h4>

 <blockquote>
    
    The dataset used is the Crop dataset.We have implemented SVM to predict crop based on attributes available. 
    Libraries used:
         1.Pandas
         2.Sci-Kit learn
         3.Numpy
 </blockquote>

In [36]:
import pandas as pd
from sklearn import svm
from sklearn import model_selection
from sklearn import metrics
from sklearn import preprocessing
import numpy as np

In [37]:
data=pd.read_csv("./new_dataset5.csv")
temp=data.copy()

<h4>Looking at the data</h4>

In [38]:
print(data.head())

        Crop  Temperature  Rainfall  Humidity
0      Wheat           34        75        68
1      Wheat           34        75        71
2      Wheat           34        67        71
3  Field Pea           33        58        74
4      Wheat           35        86        68


In [39]:
y=temp['Crop']
x=temp.drop('Crop',1)

In [40]:
y.value_counts()

Rap seed     250
Wheat        250
SugarCane    250
Field Pea    250
Gram         250
Rice         250
Name: Crop, dtype: int64

<h4>Crop name is a categorical attribute.We convert the categorical attribute to numerical attribute by a simple mapping.<h4>

In [41]:
label=preprocessing.LabelEncoder()
y=label.fit_transform(y)

In [42]:
np.unique(y)

array([0, 1, 2, 3, 4, 5])

In [43]:
print(x.head())

   Temperature  Rainfall  Humidity
0           34        75        68
1           34        75        71
2           34        67        71
3           33        58        74
4           35        86        68


In [44]:
sample_size=1500

In [45]:
y=y[:sample_size]
x=x[:sample_size]

In [46]:
print(x.shape,y.shape)

(1500, 3) (1500,)


<h2>Check if dataset has missing values</h2>

In [47]:
if 'True' in x.isnull():
    print("Missing")
else:
    print("No missing data")

No missing data


<h4>Split the dataset into test and train data<h4>

In [48]:
x_train,x_test,y_train,y_test=model_selection.train_test_split(x,y,test_size=0.3)

<h2>Normalization of data</h2>
<blockquote>The dataset has to be normalized before it is sent to any model.We can do normalization using MinMax normalization or using ZScore normalization.Both are shown</blockquote>


In [49]:
scaler_zscore = preprocessing.StandardScaler()
scaler_minmax=preprocessing.MinMaxScaler()

In [50]:
def normalize(df,choice,a):
    if choice==1:
        if a=='train':
            scaler_minmax.fit(df)
        zx = scaler_minmax.transform(df)
        return zx
    elif choice==2:
        if a=='train':
            scaler_zscore.fit(df)
        zx = scaler_zscore.transform(df)
        return zx

In [51]:
x_train_zscore=normalize(x_train,2,'train')
x_test_zscore=normalize(x_test,2,'test')
x_train_minmax=normalize(x_train,1,'train')
x_test_minmax=normalize(x_test,1,'test')


In [52]:
print(x_train_zscore.shape,y_train.shape)

(1050, 3) (1050,)


In [53]:
print(y_train)

[5 2 1 ... 3 2 1]


<h4>Correlation matrix</h4>

In [61]:
corr_matrix = x.corr()
corr_matrix

Temperature  Rainfall  Humidity
Temperature     1.000000 -0.007428 -0.084657
Rainfall       -0.007428  1.000000 -0.004254
Humidity       -0.084657 -0.004254  1.000000

<h3>Training the SVM</h3>
<blockquote>
    The gamma parameter defines how far the influence of a single training example reaches, with low values meaning ‘far’ and high values meaning ‘close’. The gamma parameters can be seen as the inverse of the radius of influence of samples selected by the model as support vectors.

The C parameter trades off correct classification of training examples against maximization of the decision function’s margin. For larger values of C, a smaller margin will be accepted if the decision function is better at classifying all training points correctly. A lower C will encourage a larger margin, therefore a simpler decision function, at the cost of training accuracy. In other words C behaves as a regularization parameter in the SVM.
</blockquote>

In [54]:
param_grid = {'C': [0.1, 1, 10, 100, 1000],  
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
              'kernel': ['rbf','linear','poly','sigmoid']}  
  
grid = model_selection.GridSearchCV(svm.SVC(), param_grid, refit = True, verbose = 3) 
  
# fitting the model for grid search 
grid.fit(x_train_zscore, y_train) 

D:\Softwares\Anaconda\envs\coding\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.587, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.611, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.587, total=   0.1s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.650, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.649, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.642, total=   0.0s
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV] .........

[CV] . C=0.1, gamma=0.0001, kernel=sigmoid, score=0.345, total=   0.1s
[CV] C=0.1, gamma=0.0001, kernel=sigmoid .............................
[CV] . C=0.1, gamma=0.0001, kernel=sigmoid, score=0.171, total=   0.1s
[CV] C=0.1, gamma=0.0001, kernel=sigmoid .............................
[CV] . C=0.1, gamma=0.0001, kernel=sigmoid, score=0.172, total=   0.1s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ............ C=1, gamma=1, kernel=rbf, score=0.704, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ............ C=1, gamma=1, kernel=rbf, score=0.666, total=   0.0s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ............ C=1, gamma=1, kernel=rbf, score=0.648, total=   0.0s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ......... C=1, gamma=1, kernel=linear, score=0.729, total=   0.0s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] .

[CV] C=1, gamma=0.0001, kernel=poly ..................................
[CV] ...... C=1, gamma=0.0001, kernel=poly, score=0.171, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=poly ..................................
[CV] ...... C=1, gamma=0.0001, kernel=poly, score=0.172, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=sigmoid ...............................
[CV] ... C=1, gamma=0.0001, kernel=sigmoid, score=0.345, total=   0.1s
[CV] C=1, gamma=0.0001, kernel=sigmoid ...............................
[CV] ... C=1, gamma=0.0001, kernel=sigmoid, score=0.171, total=   0.1s
[CV] C=1, gamma=0.0001, kernel=sigmoid ...............................
[CV] ... C=1, gamma=0.0001, kernel=sigmoid, score=0.172, total=   0.1s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.738, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.740, total=   0.0s
[CV] C

[CV] ..... C=10, gamma=0.0001, kernel=poly, score=0.171, total=   0.0s
[CV] C=10, gamma=0.0001, kernel=poly .................................
[CV] ..... C=10, gamma=0.0001, kernel=poly, score=0.172, total=   0.0s
[CV] C=10, gamma=0.0001, kernel=sigmoid ..............................
[CV] .. C=10, gamma=0.0001, kernel=sigmoid, score=0.345, total=   0.1s
[CV] C=10, gamma=0.0001, kernel=sigmoid ..............................
[CV] .. C=10, gamma=0.0001, kernel=sigmoid, score=0.171, total=   0.1s
[CV] C=10, gamma=0.0001, kernel=sigmoid ..............................
[CV] .. C=10, gamma=0.0001, kernel=sigmoid, score=0.172, total=   0.1s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.735, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.751, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .

[CV] . C=100, gamma=0.0001, kernel=sigmoid, score=0.443, total=   0.1s
[CV] C=100, gamma=0.0001, kernel=sigmoid .............................
[CV] . C=100, gamma=0.0001, kernel=sigmoid, score=0.421, total=   0.1s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.746, total=   0.1s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.771, total=   0.1s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.748, total=   0.1s
[CV] C=1000, gamma=1, kernel=linear ..................................
[CV] ...... C=1000, gamma=1, kernel=linear, score=0.746, total=   0.3s
[CV] C=1000, gamma=1, kernel=linear ..................................
[CV] ...... C=1000, gamma=1, kernel=linear, score=0.797, total=   1.0s
[CV] C=1000, gamma=1, kernel=linear ..................................
[CV] .

[CV]  C=1000, gamma=0.0001, kernel=sigmoid, score=0.642, total=   0.0s


[Parallel(n_jobs=1)]: Done 300 out of 300 | elapsed:   38.3s finished
D:\Softwares\Anaconda\envs\coding\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf', 'linear', 'poly', 'sigmoid']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [55]:
print(grid.best_estimator_)
y_pred = grid.predict(x_test_zscore)
acc1=metrics.accuracy_score(y_test,y_pred)
print("Testing Accuracy for zscore normalization: ",acc1)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
Testing Accuracy for zscore normalization:  0.6933333333333334


In [56]:
grid.fit(x_train_minmax, y_train)


D:\Softwares\Anaconda\envs\coding\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.385, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.397, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.430, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.425, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.406, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.424, total=   0.0s
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV] ......... C=0.1, gamma=1, kernel=poly, score=0.396, total=   0.0s
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV] ......... C=0.1, gamma=1, kernel=poly, score=0.437, total=   0.0s
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV] ......... C=0.1, gamma=1, kernel=poly, score=0.418, total=   0.0s
[CV] C=0.1, gamma=1, kernel=sigmoid ..................................
[CV] ...... C=0.1, gamma=1, kernel=sigmoid, score=0.427, total=   0.1s
[CV] C=0.1, gamma=1, kernel=sigmoid ..................................
[CV] .

[CV] ......... C=1, gamma=1, kernel=linear, score=0.646, total=   0.0s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ......... C=1, gamma=1, kernel=linear, score=0.636, total=   0.0s
[CV] C=1, gamma=1, kernel=poly .......................................
[CV] ........... C=1, gamma=1, kernel=poly, score=0.516, total=   0.0s
[CV] C=1, gamma=1, kernel=poly .......................................
[CV] ........... C=1, gamma=1, kernel=poly, score=0.563, total=   0.0s
[CV] C=1, gamma=1, kernel=poly .......................................
[CV] ........... C=1, gamma=1, kernel=poly, score=0.556, total=   0.0s
[CV] C=1, gamma=1, kernel=sigmoid ....................................
[CV] ........ C=1, gamma=1, kernel=sigmoid, score=0.433, total=   0.0s
[CV] C=1, gamma=1, kernel=sigmoid ....................................
[CV] ........ C=1, gamma=1, kernel=sigmoid, score=0.446, total=   0.0s
[CV] C=1, gamma=1, kernel=sigmoid ....................................
[CV] .

[CV] ....... C=10, gamma=1, kernel=sigmoid, score=0.356, total=   0.0s
[CV] C=10, gamma=1, kernel=sigmoid ...................................
[CV] ....... C=10, gamma=1, kernel=sigmoid, score=0.334, total=   0.0s
[CV] C=10, gamma=1, kernel=sigmoid ...................................
[CV] ....... C=10, gamma=1, kernel=sigmoid, score=0.367, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.667, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.649, total=   0.0s
[CV] C=10, gamma=0.1, kernel=rbf .....................................
[CV] ......... C=10, gamma=0.1, kernel=rbf, score=0.662, total=   0.0s
[CV] C=10, gamma=0.1, kernel=linear ..................................
[CV] ...... C=10, gamma=0.1, kernel=linear, score=0.729, total=   0.0s
[CV] C=10, gamma=0.1, kernel=linear ..................................
[CV] .

[CV] ...... C=100, gamma=1, kernel=sigmoid, score=0.348, total=   0.0s
[CV] C=100, gamma=1, kernel=sigmoid ..................................
[CV] ...... C=100, gamma=1, kernel=sigmoid, score=0.331, total=   0.0s
[CV] C=100, gamma=1, kernel=sigmoid ..................................
[CV] ...... C=100, gamma=1, kernel=sigmoid, score=0.341, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.732, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.769, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.768, total=   0.0s
[CV] C=100, gamma=0.1, kernel=linear .................................
[CV] ..... C=100, gamma=0.1, kernel=linear, score=0.752, total=   0.0s
[CV] C=100, gamma=0.1, kernel=linear .................................
[CV] .

[CV] ........ C=1000, gamma=1, kernel=poly, score=0.726, total=   0.1s
[CV] C=1000, gamma=1, kernel=poly ....................................
[CV] ........ C=1000, gamma=1, kernel=poly, score=0.751, total=   0.1s
[CV] C=1000, gamma=1, kernel=sigmoid .................................
[CV] ..... C=1000, gamma=1, kernel=sigmoid, score=0.339, total=   0.0s
[CV] C=1000, gamma=1, kernel=sigmoid .................................
[CV] ..... C=1000, gamma=1, kernel=sigmoid, score=0.306, total=   0.0s
[CV] C=1000, gamma=1, kernel=sigmoid .................................
[CV] ..... C=1000, gamma=1, kernel=sigmoid, score=0.338, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.735, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.771, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] .

[Parallel(n_jobs=1)]: Done 300 out of 300 | elapsed:   11.4s finished
D:\Softwares\Anaconda\envs\coding\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf', 'linear', 'poly', 'sigmoid']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [57]:
print(grid.best_estimator_)
y_pred = grid.predict(x_test_minmax)
acc2=metrics.accuracy_score(y_test,y_pred)
print("Testing Accuracy for minmax normalization: ",acc2)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
Testing Accuracy for minmax normalization:  0.7444444444444445


<h4>Confusion Matrix</h4>

In [59]:
print(metrics.confusion_matrix(y_test,y_pred))

[[54 18 13  0  0  0]
 [ 5 35 36  0  0  0]
 [ 2 39 35  0  0  0]
 [ 0  0  0 70  0  0]
 [ 0  0  0  0 69  0]
 [ 2  0  0  0  0 72]]


<h4>Classification Report</h4>

In [60]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.64      0.73        85
           1       0.38      0.46      0.42        76
           2       0.42      0.46      0.44        76
           3       1.00      1.00      1.00        70
           4       1.00      1.00      1.00        69
           5       1.00      0.97      0.99        74

    accuracy                           0.74       450
   macro avg       0.78      0.75      0.76       450
weighted avg       0.77      0.74      0.75       450

